// Buzzer
#define BUZZER_PORT GPIOC->ODR
// Motor
#define MOTOR_CONTROL_PORT GPIOD->ODR
#define MOTOR_DIRECTION_PORT GPIOD->ODR
#define MOTOR_SPEED_FEEDBACK_PORT GPIOE->IDR 
// Display
#define DISPLAY_PORT GPIOD->ODR
// Buttons
#define PROG_SEL_1_PORT GPIOE->IDR
#define PROG_SEL_2_PORT GPIOE->IDR
#define PROG_SEL_3_PORT GPIOE->IDR
#define ACCEPT_BUTTON_PORT GPIOE->IDR
#define CANCEL_BUTTON_PORT GPIOE->IDR
// Door
#define DOOR_OPEN_CLOSE_PORT GPIOE->IDR
// Reset latches
#define RESET_LATCHES_PORT GPIOD->ODR
